### ISSUE TITLE
Allow calling "plain"/non JS.* events from execJS

### ISSUE THREAD

**Issue by tmjoen** [phoenixframework/phoenix_live_view#2249]
### Environment

* Elixir version (elixir -v): 1.14.0
* Phoenix version (mix deps): phoenix 1.7.0-dev
* Phoenix LiveView version (mix deps): 0.18.1
* Operating system: OSX 12.3
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome/Firefox/Safari
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:
Yes
### Actual behavior

I have a `ConfirmClick` hook for deleting entries:
```elixir
 <button
    id={"action_#{@listing.name}_delete_entry_#{@entry.id}"}
    phx-hook="Brando.ConfirmClick"
    phx-confirm-click-message={gettext("Are you sure you want to delete this entry?")}
    phx-confirm-click="delete_entry"
    phx-value-language={@language}
    phx-value-id={@entry.id}>
    <%= gettext "Delete entry" %>
  </button>
```

The hook shows a dialog with the `phx-confirm-click-message` and if the dialog is accepted it will try to `liveSocket.execJS` the value of phx-confirm-click:

```es6
  mounted() {
    this.el.addEventListener('click', e => {
      e.preventDefault()
      e.stopPropagation()

      const event = this.el.getAttribute('phx-confirm-click')
      const message = this.el.getAttribute('phx-confirm-click-message')

      alertConfirm('OBS', message, confirmed => {
        if (confirmed !== false) {
          liveSocket.execJS(this.el, event)
        }
      })
    })
  }
```

This worked in 0.17.X. In 0.18.1 this fails with:

```
js.js:14 Uncaught TypeError: this[kind] is not a function
    at js.js:14:22
    at Array.forEach (<anonymous>)
    at js.js:13:40
    at Array.forEach (<anonymous>)
    at Object.exec (js.js:9:14)
    at live_socket.js:233:31
    at LiveSocket.owner (live_socket.js:408:15)
    at LiveSocket.execJS (live_socket.js:233:10)
    at Object.callback (index.js:15:26)
    at Object.dialogBeforeClose (vex.dialog.js:500:19)
```

When inspecting `kind` it is `null` here, probably since I'm not using a `JS` command(?):

```es6
this[`exec_${kind}`](eventType, phxEvent, view, sourceEl, el, args)
```

So calling `liveSocket.execJS` with a "plain" event ("my_event"), errors. When wrapping the plain event in `JS.push("my_event")` it works. It would be nice if the "old" style worked since in my case these are dynamically created buttons from a schema where I just pass `[event: "delete_entry", label: "Delete entry"]` and automatically create `phx-value-{id/language}` properties.

### Expected behavior

Be able to call "old style" plain event names from `execJS`

**Comment by chrismccord** [comment]
Your confirm-click attribute should be a JS.push command and then your are golden. ExecJS is about executing JS commands do if it worked before it was an accident. Thanks!

**Comment by tmjoen** [comment]
Thanks! I'll just write a check that will wrap my legacy "plain" events in JS.push
