### ISSUE TITLE
Regression: this.__view.cancelSubmit is not a function

### ISSUE THREAD

**Issue by serpent213** [phoenixframework/phoenix_live_view#3446]
### Environment

* Elixir version (elixir -v): Elixir 1.16.2 (compiled with Erlang/OTP 25)
* Phoenix version (mix deps): locked at 1.7.14 (phoenix) c7859bc5
* Phoenix LiveView version (mix deps): locked at 65614bb (branch: main)
* Operating system: macOS/Darwin with [devenv](https://devenv.sh) container
* Browsers you attempted to reproduce this bug on (the more the merrier): Safari, Firefox, Brave
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

I got a single `<.live_file_input>` on my page with `max_entries: 1` and `auto_upload: true`, preview rendering, no cancel button. Everything works fine, but in case I decide to replace the (auto-uploaded) image file (via button or drag & drop), the following pops up in the console:

```js
Uncaught TypeError: this.__view.cancelSubmit is not a function
    at ViewHook.updated (hooks.js:24:23)
    at ViewHook.__updated (view_hook.js:34:37)
    at view.js:485:55
    at dom_patch.js:79:56
    at Array.forEach (<anonymous>)
    at DOMPatch.trackAfter (dom_patch.js:79:36)
    at dom_patch.js:340:32
    at Array.forEach (<anonymous>)
    at DOMPatch.perform (dom_patch.js:340:13)
    at View.performPatch (view.js:493:11)
```

### Expected behavior

No error, worked fine with 1.0.0-rc6.

Please let me know if you need more information or a demo.

**Comment by SteffenDE** [comment]
Thank you for reporting this! Fixed by https://github.com/phoenixframework/phoenix_live_view/commit/bf177ce6ca8ebd273a3fd3711160ef0ca9db9f8d. Let me know if you encounter any more issues :)

I'll try to add a test case for this later (probably earliest next week...).

**Comment by serpent213** [comment]
Thank you for the quick fix, fellow Steffen, error is gone again indeed!  🙂
