### ISSUE TITLE
Conditionally rendered HTML tags from .leex throw compilation errors in .heex

### ISSUE THREAD

**Issue by njwest** [phoenixframework/phoenix_live_view#1774]
I assume this is a feature rather than a bug, but I think it merits upgrade documentation as it is a quirk of upgrading from phx 1.5-era LiveView (0.15.x). 

### Environment

* Elixir version (elixir -v): Elixir 1.12.2 (compiled with Erlang/OTP 24)
* Phoenix version (mix deps): * phoenix 1.6.2 
* Phoenix LiveView version (mix deps): * phoenix_live_view 0.17.5
* Operating system: macOS 10.14.x
* Browsers you attempted to reproduce this bug on (the more the merrier): Not applicable

### Actual behavior
Conditionally rendered HTML tags in .heex templates that worked in LiveView 0.15.x .leex templates now throw compilation errors.

The code:

```elixir
<%= if @boolean_val do %>
   <button type="button" aria-current="content-page" id="current-page-button">
<% else %>
   <button type="button" id={"page-#{page_number}-button"} phx-click="load-page" phx-value-target-page={page_number} phx-target={@myself}>
<% end %>
      <%= page_number %>
   </button>
```

The error ("missing opening tag", or missing the tag rendered conditionally):

```elixir
== Compilation error in file lib/my_app_web/live/components/content_card/content_card.ex ==
** (Phoenix.LiveView.HTMLTokenizer.ParseError) lib/type_type_pass_web/live/_components/room_card/room_card.html.heex:127:17: missing opening tag for </button>
    (phoenix_live_view 0.17.5) lib/phoenix_live_view/html_engine.ex:227: Phoenix.LiveView.HTMLEngine.pop_tag!/2
    (phoenix_live_view 0.17.5) lib/phoenix_live_view/html_engine.ex:432: Phoenix.LiveView.HTMLEngine.handle_token/2
    (elixir 1.12.2) lib/enum.ex:2385: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix_live_view 0.17.5) lib/phoenix_live_view/html_engine.ex:86: Phoenix.LiveView.HTMLEngine.handle_end/1
    (eex 1.12.2) lib/eex/compiler.ex:189: EEx.Compiler.wrap_expr/5
    (eex 1.12.2) lib/eex/compiler.ex:138: EEx.Compiler.generate_buffer/4
    (eex 1.12.2) lib/eex/compiler.ex:80: EEx.Compiler.generate_buffer/4
    (phoenix_live_view 0.17.5) expanding macro: Phoenix.LiveView.Renderer.__before_compile__/1
    lib/type_type_pass_web/live/_components/room_card/room_card.ex:1: LiveComponents.RoomCard (module)
    (elixir 1.12.2) lib/kernel/parallel_compiler.ex:319: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```

### Expected behavior

I expected these conditional statements to still work and render relevant HTML, although I can see why they wouldn't with many of the optimizations/component composition functionality added in recent LiveView releases that render these in-template patterns unnecessary.

**Comment by josevalim** [comment]
Yes, the error message is correct. I honestly do not expect the documentation to be very helpful here because I think this is a pattern mostly from folks updating code. If folks will continue stumbling into this in the future, then we can try to find the best approach to document it. Thanks!

**Comment by njwest** [comment]
Thanks for the feedback José, on one hand this upgrade is frustrating because I have to clean up my old quick and dirty code, on the other hand this upgrade is amazing because I have to clean up my old quick and dirty code.
